FROM node@sha256:8ea2348b068a9544dae7317b4f3aafcdc032df1647bb7d768a05a5cad1a7683f
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && \
    addgroup -S app && \
    adduser -S -G app app && \
    chown -R app:app /app
USER app

EXPOSE 5173

CMD ["npx", "vite", "--host", "0.0.0.0", "--port", "5173"]
