"""Shared registry snapshot for the middle-tier registry bridge."""

from __future__ import annotations

from typing import Any


def _agent(
    agent_id: str,
    name: str,
    category: str,
    description: str,
    capabilities: list[str],
    *,
    enabled: bool = False,
    default_tools: list[str] | None = None,
    icon: str = "Bot",
    color: str = "#4fc3f7",
) -> dict[str, Any]:
    return {
        "id": agent_id,
        "name": name,
        "description": description,
        "category": category,
        "capabilities": capabilities,
        "enabled": enabled,
        "default_tools": default_tools or [],
        "icon": icon,
        "color": color,
        "parameters": {
            "enabled": enabled,
            "category": category,
            "origin": "registry_snapshot",
        },
    }


def _skill(
    skill_id: str,
    name: str,
    category: str,
    description: str,
    tags: list[str],
    *,
    agent_types: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "id": skill_id,
        "name": name,
        "description": description,
        "category": category,
        "agent_types": agent_types or [category],
        "tags": tags,
    }


AGENT_CATEGORIES = [
    "coding",
    "research",
    "devops",
    "communication",
    "creative",
    "education",
    "data",
    "productivity",
]

SKILL_CATEGORIES = [
    "coding",
    "research",
    "devops",
    "communication",
    "creative",
    "education",
    "data",
    "productivity",
    "meta",
]

AGENT_CATALOG: list[dict[str, Any]] = [
    _agent(
        "coding",
        "Coding Agent",
        "coding",
        "General-purpose coding specialist for implementation, debugging, and review.",
        ["code", "python", "typescript", "debug"],
        enabled=True,
        default_tools=["git", "pytest", "ruff"],
        icon="Code",
    ),
    _agent(
        "code-reviewer",
        "Code Reviewer",
        "coding",
        "Reviews pull requests for correctness, style, and security issues.",
        ["review", "lint", "security"],
        enabled=True,
        default_tools=["git", "ruff"],
        icon="ShieldCheck",
    ),
    _agent(
        "debugging",
        "Debugging Agent",
        "coding",
        "Tracks down runtime failures and test regressions.",
        ["debug", "trace", "test"],
        default_tools=["pytest", "pdb"],
        icon="Bug",
    ),
    _agent(
        "test-automation",
        "Test Automation Agent",
        "coding",
        "Writes and runs unit, integration, and end-to-end tests.",
        ["test", "coverage", "qa"],
        enabled=True,
        default_tools=["pytest", "vitest"],
        icon="FlaskConical",
    ),
    _agent(
        "research",
        "Research Agent",
        "research",
        "Finds sources, summarizes findings, and compares evidence.",
        ["search", "summarize", "analyze"],
        enabled=True,
        default_tools=["browser", "notes"],
        icon="BookOpen",
    ),
    _agent(
        "research-assistant",
        "Research Assistant",
        "research",
        "Performs web research and produces concise briefs.",
        ["search", "brief", "source"],
        enabled=True,
        default_tools=["browser", "reader"],
        icon="BookMarked",
    ),
    _agent(
        "fact-checker",
        "Fact Checker",
        "research",
        "Verifies claims against authoritative sources.",
        ["verify", "cite", "score"],
        default_tools=["browser", "citation"],
        icon="SearchCheck",
    ),
    _agent(
        "devops",
        "DevOps Agent",
        "devops",
        "Handles deployments, monitoring, and incident response.",
        ["deploy", "monitor", "incident"],
        enabled=True,
        default_tools=["kubectl", "docker"],
        icon="Server",
    ),
    _agent(
        "infrastructure-monitor",
        "Infrastructure Monitor",
        "devops",
        "Observes system health and alerts on anomalies.",
        ["monitor", "alert", "metrics"],
        enabled=True,
        default_tools=["prometheus", "logs"],
        icon="Activity",
    ),
    _agent(
        "incident-responder",
        "Incident Responder",
        "devops",
        "Triage and remediation playbooks for outages.",
        ["incident", "rollback", "sre"],
        default_tools=["runbook", "pager"],
        icon="TriangleAlert",
    ),
    _agent(
        "security",
        "Security Agent",
        "devops",
        "Scans for vulnerabilities and hardens delivery pipelines.",
        ["scan", "audit", "compliance"],
        enabled=True,
        default_tools=["scanner", "policy"],
        icon="Shield",
    ),
    _agent(
        "communication",
        "Communication Agent",
        "communication",
        "Drafts messages and routes human communication.",
        ["email", "message", "translate"],
        enabled=True,
        default_tools=["mail", "chat"],
        icon="MessageSquare",
    ),
    _agent(
        "email-drafter",
        "Email Drafter",
        "communication",
        "Writes professional emails and follow-ups.",
        ["draft", "rewrite", "tone"],
        default_tools=["mail"],
        icon="Mail",
    ),
    _agent(
        "translator",
        "Translator",
        "communication",
        "Translates between languages while preserving intent.",
        ["translate", "localize", "summarize"],
        default_tools=["dictionary"],
        icon="Languages",
    ),
    _agent(
        "creative",
        "Creative Agent",
        "creative",
        "Writes copy, stories, and ideation prompts.",
        ["write", "brainstorm", "story"],
        enabled=True,
        default_tools=["outline"],
        icon="PenTool",
    ),
    _agent(
        "creative-writer",
        "Creative Writer",
        "creative",
        "Generates stories, poems, and marketing copy.",
        ["write", "story", "style"],
        default_tools=["draft"],
        icon="Feather",
    ),
    _agent(
        "education",
        "Education Agent",
        "education",
        "Explains concepts and adapts instruction.",
        ["teach", "quiz", "explain"],
        enabled=True,
        default_tools=["lesson", "quiz"],
        icon="GraduationCap",
    ),
    _agent(
        "tutor",
        "Tutor",
        "education",
        "Socratic teaching and guided practice.",
        ["teach", "explain", "assess"],
        enabled=True,
        default_tools=["lesson"],
        icon="Users",
    ),
    _agent(
        "data",
        "Data Agent",
        "data",
        "Analyzes datasets and communicates insights.",
        ["analysis", "sql", "visualize"],
        enabled=True,
        default_tools=["sql", "chart"],
        icon="Database",
    ),
    _agent(
        "data-analyst",
        "Data Analyst",
        "data",
        "Turns datasets into plots and narratives.",
        ["analyze", "visualize", "report"],
        enabled=True,
        default_tools=["sql", "notebook"],
        icon="BarChart3",
    ),
    _agent(
        "productivity",
        "Productivity Agent",
        "productivity",
        "Organizes tasks, calendars, and notes.",
        ["schedule", "task", "notes"],
        enabled=True,
        default_tools=["calendar", "tasks"],
        icon="Calendar",
    ),
    _agent(
        "scheduler",
        "Scheduler",
        "productivity",
        "Coordinates meetings and time blocks.",
        ["calendar", "conflict", "plan"],
        enabled=True,
        default_tools=["calendar"],
        icon="Clock",
    ),
]

SKILL_CATALOG: list[dict[str, Any]] = [
    _skill(
        "code_generation",
        "Code Generation",
        "coding",
        "Generate code in any language from natural language descriptions.",
        ["python", "typescript", "rust"],
    ),
    _skill(
        "code_review",
        "Code Review",
        "coding",
        "Review PRs for bugs, style, and security vulnerabilities.",
        ["quality", "security"],
    ),
    _skill(
        "debugging",
        "Debugging",
        "coding",
        "Find and fix bugs with systematic root cause analysis.",
        ["testing", "quality"],
    ),
    _skill(
        "refactoring",
        "Refactoring",
        "coding",
        "Restructure code for better maintainability without changing behavior.",
        ["quality", "patterns"],
    ),
    _skill(
        "unit_testing",
        "Unit Testing",
        "coding",
        "Generate and run unit, integration, and e2e tests.",
        ["testing", "coverage"],
    ),
    _skill(
        "static_analysis",
        "Static Analysis",
        "coding",
        "Analyze code without running it to find potential issues.",
        ["quality", "security"],
    ),
    _skill(
        "web_search",
        "Web Search",
        "research",
        "Search the web and synthesize findings into coherent results.",
        ["search", "information"],
    ),
    _skill(
        "fact_checking",
        "Fact Checking",
        "research",
        "Verify claims against authoritative sources with confidence scoring.",
        ["accuracy", "verification"],
    ),
    _skill(
        "data_analysis",
        "Data Analysis",
        "research",
        "Analyze datasets and extract actionable insights.",
        ["statistics", "analytics"],
    ),
    _skill(
        "summarization",
        "Summarization",
        "research",
        "Condense long texts into concise, accurate summaries.",
        ["reading", "efficiency"],
    ),
    _skill(
        "infrastructure_monitoring",
        "Infrastructure Monitoring",
        "devops",
        "Monitor system health, track metrics, and alert on anomalies.",
        ["observability", "alerts"],
    ),
    _skill(
        "deployment",
        "Deployment",
        "devops",
        "Deploy services, manage releases, and rollback when needed.",
        ["ci/cd", "kubernetes"],
    ),
    _skill(
        "incident_response",
        "Incident Response",
        "devops",
        "Respond to and resolve system incidents with runbooks.",
        ["reliability", "sre"],
    ),
    _skill(
        "security_scanning",
        "Security Scanning",
        "devops",
        "Scan for vulnerabilities, misconfigurations, and compliance gaps.",
        ["vulnerability", "compliance"],
    ),
    _skill(
        "log_analysis",
        "Log Analysis",
        "devops",
        "Parse and analyze log files for patterns and anomalies.",
        ["observability", "debugging"],
    ),
    _skill(
        "email_drafting",
        "Email Drafting",
        "communication",
        "Draft professional emails for any context or audience.",
        ["writing", "professional"],
    ),
    _skill(
        "content_creation",
        "Content Creation",
        "communication",
        "Create engaging content for any platform or medium.",
        ["marketing", "writing"],
    ),
    _skill(
        "customer_support",
        "Customer Support",
        "communication",
        "Handle customer inquiries, triage issues, and provide solutions.",
        ["service", "ticketing"],
    ),
    _skill(
        "translation",
        "Translation",
        "communication",
        "Translate text between languages while preserving meaning.",
        ["languages", "international"],
    ),
    _skill(
        "creative_writing",
        "Creative Writing",
        "creative",
        "Write stories, poems, and creative content with vivid language.",
        ["writing", "storytelling"],
    ),
    _skill(
        "copywriting",
        "Copywriting",
        "creative",
        "Write persuasive marketing copy and advertising content.",
        ["marketing", "writing"],
    ),
    _skill(
        "brainstorming",
        "Brainstorming",
        "creative",
        "Generate creative ideas and novel solutions to problems.",
        ["ideation", "creativity"],
    ),
    _skill(
        "teaching",
        "Teaching",
        "education",
        "Explain concepts with adaptive pedagogy and Socratic dialogue.",
        ["learning", "pedagogy"],
    ),
    _skill(
        "quiz_generation",
        "Quiz Generation",
        "education",
        "Create quizzes and assessments to test knowledge.",
        ["assessment", "learning"],
    ),
    _skill(
        "language_learning",
        "Language Learning",
        "education",
        "Practice conversations, grammar, and vocabulary in new languages.",
        ["languages", "practice"],
    ),
    _skill(
        "sql_querying",
        "SQL Querying",
        "data",
        "Write, optimize, and debug SQL queries across databases.",
        ["database", "analytics"],
    ),
    _skill(
        "data_visualization",
        "Data Visualization",
        "data",
        "Create charts, graphs, and dashboards from any data.",
        ["charts", "dashboard"],
    ),
    _skill(
        "database_design",
        "Database Design",
        "data",
        "Design schemas, optimize queries, and plan migrations.",
        ["schema", "optimization"],
    ),
    _skill(
        "scheduling",
        "Scheduling",
        "productivity",
        "Manage calendars, schedule events, and resolve conflicts.",
        ["calendar", "time"],
    ),
    _skill(
        "task_management",
        "Task Management",
        "productivity",
        "Track tasks, manage sprints, and organize workflows.",
        ["agile", "organization"],
    ),
    _skill(
        "note_taking",
        "Note Taking",
        "productivity",
        "Take, organize, and summarize meeting notes and documents.",
        ["documentation", "organization"],
    ),
    _skill(
        "prompt_engineering",
        "Prompt Engineering",
        "meta",
        "Design and optimize prompts for LLMs across use cases.",
        ["optimization", "llm"],
    ),
    _skill(
        "tool_creation",
        "Tool Creation",
        "meta",
        "Create new tools and integrations for the agent platform.",
        ["development", "extensibility"],
    ),
    _skill(
        "workflow_automation",
        "Workflow Automation",
        "meta",
        "Automate multi-step workflows across tools and services.",
        ["automation", "efficiency"],
    ),
    _skill(
        "agent_orchestration",
        "Agent Orchestration",
        "meta",
        "Coordinate multiple agents across a shared task workflow.",
        ["multi-agent", "routing"],
    ),
    _skill(
        "prompt_analysis",
        "Prompt Analysis",
        "meta",
        "Evaluate prompt quality, safety, and response coverage.",
        ["evaluation", "llm"],
    ),
]


def get_registry_snapshot() -> dict[str, Any]:
    return {
        "agents": [dict(agent) for agent in AGENT_CATALOG],
        "agent_categories": list(AGENT_CATEGORIES),
        "skills": [dict(skill) for skill in SKILL_CATALOG],
        "skill_categories": list(SKILL_CATEGORIES),
    }
