/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function computeTokenBudget(text: string, maxTokens: number, options?: TokenCountOptions | undefined | null): TokenBudget

export declare function countTokens(text: string, options?: TokenCountOptions | undefined | null): TokenCountResult

export declare function estimateTokensForMessages(messages: Array<string>): number

export declare function formatTokenCount(count: number): string

export interface TokenBudget {
  available: number
  used: number
  remaining: number
  fractionUsed: number
}

export interface TokenCountOptions {
  approximate?: boolean
  modelContext?: number
}

export interface TokenCountResult {
  characters: number
  words: number
  sentences: number
  estimatedTokens: number
  lines: number
  graphemeClusters: number
}

export declare function truncateToBudget(text: string, maxTokens: number, options?: TokenCountOptions | undefined | null): string
