/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DataEngine {
  constructor()
  getAgent(id: string): AgentState | null
  listAgents(): Array<AgentState>
  upsertAgent(id: string, state: string, role: string, metricsJson: string): void
  deleteAgent(id: string): boolean
  appendActivity(command: string, success: boolean, output: string): ActivityEntry
  getActivity(limit?: number | undefined | null): Array<ActivityEntry>
  searchActivity(query: string, limit?: number | undefined | null): Array<ActivityEntry>
  addNotification(channel: string, priority: string, category: string, title: string, body: string): Notification
  getNotifications(category?: string | undefined | null, priority?: string | undefined | null, read?: boolean | undefined | null, limit?: number | undefined | null): Array<Notification>
  markNotificationRead(id: string): boolean
  markAllNotificationsRead(category?: string | undefined | null): number
  getNotificationStats(): NotificationStats
  getMemoryLayers(): Array<MemoryLayer>
  addMemoryEntry(layer: string, content: string): void
  getMemoryEntries(layer?: string | undefined | null, query?: string | undefined | null, limit?: number | undefined | null): Array<MemoryEntry>
  deleteMemoryEntry(id: string): boolean
  getConfig(key: string): string | null
  getAllConfig(): Record<string, string>
  setConfig(key: string, value: string): void
  appendLog(level: string, logger: string, message: string): void
  getLogs(level?: string | undefined | null, query?: string | undefined | null, limit?: number | undefined | null): Array<LogRecord>
  searchLogs(query: string, level?: string | undefined | null, limit?: number | undefined | null): Array<LogRecord>
  getStats(): SystemStats
  clearActivity(): number
  clearNotifications(): number
  clearLogs(): number
  exportJson(): string
  importJson(json: string): boolean
  saveToFile(path: string): boolean
  loadFromFile(path: string): boolean
  listSkills(): Array<SkillEntry>
  getSkill(id: string): SkillEntry | null
  listWorkflows(): Array<WorkflowEntry>
  getWorkflow(id: string): WorkflowEntry | null
  updateWorkflowStatus(id: string, status: string): boolean
  listModels(): Array<ModelInfo>
  getModel(id: string): ModelInfo | null
  setModelState(id: string, state: string): boolean
  listTrainingRuns(): Array<TrainingRunSummary>
  getTrainingRun(id: string): TrainingRunDetail | null
  createTrainingRun(name: string, modelId: string, totalEpochs: number): TrainingRunSummary
}

export interface ActivityEntry {
  id: string
  timestamp: number
  command: string
  success: boolean
  output: string
}

export interface AgentState {
  id: string
  state: string
  role: string
  metricsJson: string
}

export interface LogRecord {
  timestamp: string
  level: string
  logger: string
  message: string
}

export interface MemoryEntry {
  id: string
  content: string
  layer: string
  timestamp: string
  accessCount: number
  importanceScore: number
}

export interface MemoryLayer {
  name: string
  entries: number
}

export interface ModelInfo {
  id: string
  name: string
  description: string
  path: string
  parameterCount: number
  state: string
  loadedAt?: string
  source: string
}

export interface Notification {
  id: string
  timestamp: number
  channel: string
  priority: string
  category: string
  title: string
  body: string
  read: boolean
  delivered: boolean
}

export interface NotificationStats {
  unread: number
  total: number
}

export interface SearchResult {
  matches: number
  entries: Array<LogRecord>
}

export interface SkillEntry {
  id: string
  name: string
  description: string
  active: boolean
  version: string
  category: string
  riskScore: number
  allowLevel: string
  source: string
}

export interface SystemStats {
  agentCount: number
  activityCount: number
  notificationCount: number
  notificationUnread: number
  memoryEntryCount: number
  logCount: number
}

export interface TrainingDataPoint {
  step: number
  trainLoss: number
  valLoss: number
  learningRate: number
  accuracy: number
  gradNorm: number
}

export interface TrainingRunDetail {
  id: string
  name: string
  modelId: string
  status: string
  startedAt: number
  currentEpoch: number
  totalEpochs: number
  bestValLoss: number
  currentLr: number
  totalSteps: number
  steps: Array<number>
  trainLosses: Array<number>
  valLosses: Array<number>
  learningRates: Array<number>
  accuracies: Array<number>
  source: string
}

export interface TrainingRunSummary {
  id: string
  name: string
  modelId: string
  status: string
  startedAt: number
  currentEpoch: number
  totalEpochs: number
  bestValLoss: number
  currentLr: number
  totalSteps: number
  dataPointCount: number
  source: string
}

export interface WorkflowEntry {
  id: string
  name: string
  status: string
  lastRun: number
  duration: number
  eventCount: number
  source: string
}
