"""Medusa: Simple LLM Inference Acceleration with Multiple Decoding Heads.

Implements Medusa (Cai et al., arXiv:2401.10774): K auxiliary MLP heads added to
a base LLM, each predicting a future token position. Tree-based verification
accepts a greedy prefix of the candidates produced by the heads.

Reference: https://arxiv.org/abs/2401.10774
"""
from __future__ import annotations

from typing import Callable, List, Tuple

import torch
import torch.nn as nn


class MedusaHead(nn.Module):
    """Single auxiliary Medusa prediction head.

    A 1- or 2-layer MLP that maps hidden states to vocabulary logits.

    Args:
        d_model: Hidden dimension of the base model.
        vocab_size: Vocabulary size.
        n_hidden_layers: Number of hidden layers (1 or 2).
        hidden_size: Dimension of intermediate layer; defaults to d_model.
    """

    def __init__(
        self,
        d_model: int,
        vocab_size: int,
        n_hidden_layers: int = 1,
        hidden_size: int | None = None,
    ) -> None:
        super().__init__()
        if hidden_size is None:
            hidden_size = d_model

        layers: list[nn.Module] = []
        if n_hidden_layers == 1:
            layers.append(nn.Linear(d_model, hidden_size))
            layers.append(nn.SiLU())
            layers.append(nn.Linear(hidden_size, vocab_size))
        else:
            # 2-layer MLP
            layers.append(nn.Linear(d_model, hidden_size))
            layers.append(nn.SiLU())
            layers.append(nn.Linear(hidden_size, hidden_size))
            layers.append(nn.SiLU())
            layers.append(nn.Linear(hidden_size, vocab_size))

        self.mlp = nn.Sequential(*layers)

    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor:
        """Map hidden states to vocabulary logits.

        Args:
            hidden_state: (B, T, d_model)

        Returns:
            logits: (B, T, vocab_size)
        """
        return self.mlp(hidden_state)


class MedusaHeads(nn.Module):
    """K Medusa auxiliary heads operating on shared hidden states.

    Head i predicts the token at position t + i + 1 (head 0 → t+1, head 1 → t+2, …).

    Args:
        d_model: Hidden dimension of the base model.
        vocab_size: Vocabulary size.
        n_heads: Number of Medusa heads (K).
    """

    def __init__(
        self,
        d_model: int,
        vocab_size: int,
        n_heads: int = 4,
    ) -> None:
        super().__init__()
        self.n_heads = n_heads
        self.vocab_size = vocab_size
        self.heads = nn.ModuleList(
            [MedusaHead(d_model, vocab_size) for _ in range(n_heads)]
        )

    def forward(self, hidden_state: torch.Tensor) -> List[torch.Tensor]:
        """Run all K heads on the given hidden state.

        Args:
            hidden_state: (B, T, d_model)

        Returns:
            List of K tensors each of shape (B, T, vocab_size).
        """
        return [head(hidden_state) for head in self.heads]

    def predict_next_tokens(
        self,
        hidden_state: torch.Tensor,
        greedy: bool = True,
    ) -> torch.Tensor:
        """Predict next K token ids from the last position of each head.

        Args:
            hidden_state: (B, T, d_model)
            greedy: If True, use argmax; otherwise sample from softmax.

        Returns:
            token_ids: (B, n_heads) — predicted token id per head.
        """
        all_logits = self.forward(hidden_state)  # K × (B, T, vocab_size)
        preds = []
        for logits in all_logits:
            last = logits[:, -1, :]  # (B, vocab_size)
            if greedy:
                tok = last.argmax(dim=-1)  # (B,)
            else:
                probs = torch.softmax(last, dim=-1)
                tok = torch.multinomial(probs, num_samples=1).squeeze(-1)  # (B,)
            preds.append(tok)
        return torch.stack(preds, dim=1)  # (B, n_heads)


class MedusaVerifier:
    """Tree-based greedy acceptance verifier for Medusa decoding.

    Compares head predictions against the base model's auto-regressive output
    and accepts the longest consistent prefix.

    Args:
        n_heads: Number of Medusa heads (K).
    """

    def __init__(self, n_heads: int) -> None:
        self.n_heads = n_heads

    def verify(
        self,
        base_tokens: torch.Tensor,
        head_predictions: torch.Tensor,
    ) -> Tuple[torch.Tensor, int]:
        """Greedy prefix acceptance.

        Compare head_predictions[i] against base_tokens[i] for i = 0..K-1.
        Accept as long as they match; stop at first mismatch.

        Args:
            base_tokens: (γ,) tokens generated by the base model one-at-a-time,
                         where γ ≤ K.  base_tokens[i] is the ground-truth token
                         for position i.
            head_predictions: (K, γ) predictions from heads.  head_predictions[i]
                              is head i's prediction for each of the γ candidate
                              positions; in the simplest (single-step) case γ = K
                              and head_predictions[i, i] is the relevant value.

        Returns:
            (accepted_tokens, n_accepted) where accepted_tokens is the greedy-
            accepted prefix of base_tokens and n_accepted is its length.

        Note:
            For the common single-step Medusa use-case pass a 1-D base_tokens
            tensor of length K and a (K,) head_predictions tensor (the diagonal
            slice head_predictions[i] for step i).  This method handles both
            1-D head_predictions (K,) and 2-D (K, γ).
        """
        gamma = base_tokens.shape[0]

        # Normalise head_predictions to 1-D: one prediction per position
        if head_predictions.dim() == 2:
            # head_predictions[i, i] is head i's prediction for position i
            n = min(gamma, head_predictions.shape[0], head_predictions.shape[1])
            flat_preds = torch.stack(
                [head_predictions[i, i] for i in range(n)]
            )
        else:
            # Already 1-D: (K,)
            n = min(gamma, head_predictions.shape[0])
            flat_preds = head_predictions[:n]

        n_accepted = 0
        for i in range(n):
            if flat_preds[i].item() == base_tokens[i].item():
                n_accepted += 1
            else:
                break

        accepted_tokens = base_tokens[:n_accepted]
        return accepted_tokens, n_accepted


class MedusaDecoder:
    """Full inference loop combining a base model with Medusa heads.

    At each step:
    1. Run base_model_fn on current context to obtain hidden states.
    2. Use MedusaHeads to predict K candidate next tokens.
    3. Run base_model_fn one token at a time on those candidates to verify.
    4. Accept the longest consistent greedy prefix.
    5. Append accepted tokens and repeat.

    Args:
        base_model_fn: Callable ``(input_ids: LongTensor(1, T)) →
            (hidden_state: (1, T, d), logits: (1, T, V))``.
        heads: Trained MedusaHeads instance.
        n_steps: Number of candidate tokens to propose per Medusa step (K).
    """

    def __init__(
        self,
        base_model_fn: Callable[
            [torch.LongTensor], Tuple[torch.Tensor, torch.Tensor]
        ],
        heads: MedusaHeads,
        n_steps: int = 4,
    ) -> None:
        self.base_model_fn = base_model_fn
        self.heads = heads
        self.n_steps = n_steps
        self.verifier = MedusaVerifier(n_heads=heads.n_heads)

    @torch.no_grad()
    def generate(
        self,
        prompt_ids: torch.LongTensor,
        max_new_tokens: int,
    ) -> torch.LongTensor:
        """Generate tokens using Medusa tree decoding.

        Args:
            prompt_ids: (1, prompt_len) prompt token ids.
            max_new_tokens: Maximum number of new tokens to generate.

        Returns:
            new_tokens: (max_new_tokens,) generated token ids (excluding prompt).
        """
        generated: list[int] = []
        context = prompt_ids.clone()

        while len(generated) < max_new_tokens:
            remaining = max_new_tokens - len(generated)

            # --- Step 1: Get hidden states from base model on current context ---
            hidden_state, _logits = self.base_model_fn(context)
            # hidden_state: (1, T, d_model)

            # --- Step 2: Predict K candidates via Medusa heads ---
            k = min(self.n_steps, remaining)
            candidate_ids = self.heads.predict_next_tokens(
                hidden_state, greedy=True
            )  # (1, n_heads)
            candidates = candidate_ids[0, :k]  # (k,) — one per head

            # --- Step 3: Verify candidates against base model auto-regressively ---
            base_tokens_list: list[int] = []
            verify_ctx = context.clone()
            for i in range(k):
                hs, logits_v = self.base_model_fn(verify_ctx)
                next_tok = logits_v[0, -1, :].argmax().item()
                base_tokens_list.append(next_tok)
                verify_ctx = torch.cat(
                    [verify_ctx, torch.tensor([[next_tok]], dtype=torch.long)],
                    dim=1,
                )

            base_tokens = torch.tensor(base_tokens_list, dtype=torch.long)

            # --- Step 4: Greedy prefix acceptance ---
            accepted_tokens, n_accepted = self.verifier.verify(
                base_tokens, candidates
            )

            if n_accepted == 0:
                # Accept at least the base model's first token
                tok = base_tokens_list[0]
                generated.append(tok)
                context = torch.cat(
                    [context, torch.tensor([[tok]], dtype=torch.long)], dim=1
                )
            else:
                for tok in accepted_tokens.tolist():
                    if len(generated) < max_new_tokens:
                        generated.append(tok)
                context = torch.cat(
                    [
                        context,
                        torch.tensor(
                            [accepted_tokens.tolist()[:remaining]], dtype=torch.long
                        ),
                    ],
                    dim=1,
                )

        new_tokens = torch.tensor(generated[:max_new_tokens], dtype=torch.long)
        return new_tokens
