"""
HyperNetworks: small networks that generate weights for larger target networks,
enabling dynamic weight generation conditioned on task/context embeddings.
"""

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------------------------------
# WeightGenerator
# ---------------------------------------------------------------------------


class WeightGenerator(nn.Module):
    """MLP that maps a context vector to a flat weight tensor, reshaped to target_shape."""

    def __init__(self, d_context: int, target_shape: tuple[int, ...], hidden: int = 64):
        super().__init__()
        self.target_shape = target_shape
        n_params = 1
        for s in target_shape:
            n_params *= s

        self.mlp = nn.Sequential(
            nn.Linear(d_context, hidden),
            nn.ReLU(),
            nn.Linear(hidden, n_params),
        )

    def forward(self, context: torch.Tensor) -> torch.Tensor:
        """
        Args:
            context: [B, d_context]
        Returns:
            weights: [B, *target_shape]
        """
        out = self.mlp(context)  # [B, prod(target_shape)]
        return out.view(out.shape[0], *self.target_shape)


# ---------------------------------------------------------------------------
# HyperLinear
# ---------------------------------------------------------------------------


class HyperLinear(nn.Module):
    """
    A linear layer whose weight and bias are generated by a HyperNetwork
    conditioned on a context vector.
    """

    def __init__(self, d_context: int, in_features: int, out_features: int, hidden: int = 64):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        self.weight_gen = WeightGenerator(d_context, (out_features, in_features), hidden=hidden)
        self.bias_gen = WeightGenerator(d_context, (out_features,), hidden=hidden)

    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x:       [B, in_features]
            context: [B, d_context]
        Returns:
            out: [B, out_features]
        """
        W = self.weight_gen(context)  # [B, out_features, in_features]
        b = self.bias_gen(context)  # [B, out_features]
        # bmm: [B, out_features, in_features] x [B, in_features, 1] -> [B, out_features, 1]
        out = torch.bmm(W, x.unsqueeze(-1)).squeeze(-1)  # [B, out_features]
        return out + b


# ---------------------------------------------------------------------------
# HyperAttention
# ---------------------------------------------------------------------------


class HyperAttention(nn.Module):
    """
    Multi-head self-attention where the Q, K, V, O projection matrices are
    generated per-example by a HyperNetwork conditioned on a context vector.
    """

    def __init__(self, d_model: int, d_context: int, n_heads: int, hidden: int = 64):
        super().__init__()
        assert d_model % n_heads == 0, "d_model must be divisible by n_heads"  # noqa: S101
        self.d_model = d_model
        self.n_heads = n_heads
        self.d_head = d_model // n_heads
        self.scale = math.sqrt(self.d_head)

        # Each generator produces a full [d_model, d_model] projection matrix.
        self.W_q_gen = WeightGenerator(d_context, (d_model, d_model), hidden=hidden)
        self.W_k_gen = WeightGenerator(d_context, (d_model, d_model), hidden=hidden)
        self.W_v_gen = WeightGenerator(d_context, (d_model, d_model), hidden=hidden)
        self.W_o_gen = WeightGenerator(d_context, (d_model, d_model), hidden=hidden)

    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x:       [B, T, d_model]
            context: [B, d_context]
        Returns:
            out: [B, T, d_model]
        """
        B, T, D = x.shape
        H = self.n_heads
        Dh = self.d_head

        W_q = self.W_q_gen(context)  # [B, D, D]
        W_k = self.W_k_gen(context)  # [B, D, D]
        W_v = self.W_v_gen(context)  # [B, D, D]
        W_o = self.W_o_gen(context)  # [B, D, D]

        # Project: [B, T, D] @ [B, D, D]^T  ->  [B, T, D]
        # Use bmm after transposing: x is [B,T,D], W is [B,D,D]
        # We want x @ W^T  =>  bmm(x, W.transpose(-1,-2))
        Q = torch.bmm(x, W_q.transpose(-1, -2))  # [B, T, D]
        K = torch.bmm(x, W_k.transpose(-1, -2))  # [B, T, D]
        V = torch.bmm(x, W_v.transpose(-1, -2))  # [B, T, D]

        # Reshape for multi-head: [B, H, T, Dh]
        Q = Q.view(B, T, H, Dh).transpose(1, 2)  # [B, H, T, Dh]
        K = K.view(B, T, H, Dh).transpose(1, 2)
        V = V.view(B, T, H, Dh).transpose(1, 2)

        # Attention scores
        attn = torch.matmul(Q, K.transpose(-1, -2)) / self.scale  # [B, H, T, T]
        attn = F.softmax(attn, dim=-1)

        # Weighted sum
        y = torch.matmul(attn, V)  # [B, H, T, Dh]
        y = y.transpose(1, 2).contiguous().view(B, T, D)  # [B, T, D]

        # Output projection
        out = torch.bmm(y, W_o.transpose(-1, -2))  # [B, T, D]
        return out


# ---------------------------------------------------------------------------
# HyperTransformerBlock
# ---------------------------------------------------------------------------


class HyperTransformerBlock(nn.Module):
    """
    Transformer block with hyper-attention (context-conditioned Q/K/V/O projections)
    and a standard fixed FFN.
    """

    def __init__(self, d_model: int, d_context: int, n_heads: int, hidden: int = 64):
        super().__init__()
        self.hyper_attn = HyperAttention(d_model, d_context, n_heads, hidden=hidden)

        # Standard fixed FFN
        self.ffn = nn.Sequential(
            nn.Linear(d_model, 4 * d_model),
            nn.GELU(),
            nn.Linear(4 * d_model, d_model),
        )

        self.ln1 = nn.LayerNorm(d_model)
        self.ln2 = nn.LayerNorm(d_model)

    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x:       [B, T, d_model]
            context: [B, d_context]
        Returns:
            out: [B, T, d_model]
        """
        # Hyper-attention sub-layer with residual + LayerNorm
        x = self.ln1(x + self.hyper_attn(x, context))
        # FFN sub-layer with residual + LayerNorm
        x = self.ln2(x + self.ffn(x))
        return x


# ---------------------------------------------------------------------------
# TaskConditionedLM
# ---------------------------------------------------------------------------


class TaskConditionedLM(nn.Module):
    """
    Language model whose transformer blocks are conditioned on a task embedding
    via HyperNetworks.
    """

    def __init__(
        self,
        d_model: int,
        vocab_size: int,
        n_layers: int,
        n_tasks: int,
        d_context: int,
        n_heads: int = 4,
        hidden: int = 64,
    ):
        super().__init__()
        self.task_embeddings = nn.Embedding(n_tasks, d_context)
        self.embedding = nn.Embedding(vocab_size, d_model)

        self.blocks = nn.ModuleList(
            [
                HyperTransformerBlock(d_model, d_context, n_heads, hidden=hidden)
                for _ in range(n_layers)
            ]
        )

        self.lm_head = nn.Linear(d_model, vocab_size, bias=False)

    def forward(self, input_ids: torch.Tensor, task_ids: torch.Tensor) -> torch.Tensor:
        """
        Args:
            input_ids: [B, T]  integer token ids
            task_ids:  [B]     integer task ids
        Returns:
            logits: [B, T, vocab_size]
        """
        context = self.task_embeddings(task_ids)  # [B, d_context]
        x = self.embedding(input_ids)  # [B, T, d_model]

        for block in self.blocks:
            x = block(x, context)

        logits = self.lm_head(x)  # [B, T, vocab_size]
        return logits

    def compute_loss(self, input_ids: torch.Tensor, task_ids: torch.Tensor) -> torch.Tensor:
        """
        Standard next-token prediction cross-entropy loss.

        Args:
            input_ids: [B, T]
            task_ids:  [B]
        Returns:
            loss: scalar tensor
        """
        logits = self.forward(input_ids, task_ids)  # [B, T, vocab_size]
        # shift: predict token t+1 from token t
        shift_logits = logits[:, :-1, :].contiguous()  # [B, T-1, vocab_size]
        shift_labels = input_ids[:, 1:].contiguous()  # [B, T-1]
        loss = F.cross_entropy(
            shift_logits.view(-1, shift_logits.size(-1)),
            shift_labels.view(-1),
        )
        return loss


# ---------------------------------------------------------------------------
# HyperNetConfig
# ---------------------------------------------------------------------------


@dataclass
class HyperNetConfig:
    d_model: int = 32
    vocab_size: int = 64
    n_layers: int = 2
    n_heads: int = 4
    d_context: int = 16
    n_tasks: int = 4
    hidden: int = 32
