# syntax=docker/dockerfile:1
FROM python:3.14-slim@sha256:7a500125bc50693f2214e842a621440a1b1b9cbb2188f74ab045d29ed2ea5856
WORKDIR /app

RUN pip install --no-cache-dir uv && \
    uv sync --dev

EXPOSE 8080

CMD ["python", "-m", "src.serving.api_server", "--host", "0.0.0.0", "--port", "8080"]
