# syntax=docker/dockerfile:1
FROM python:3.12-slim
WORKDIR /app

RUN pip install --no-cache-dir uv && \
    uv sync --dev

EXPOSE 8080

CMD ["uvicorn", "src.serving.api_server:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
