FROM node:22-alpine@sha256:8ea2348b068a9544dae7317b4f3aafcdc032df1647bb7d768a05a5cad1a7683f
WORKDIR /app

COPY package.json ./
RUN npm install --include=dev && \
    addgroup -S aurelius && \
    adduser -S -G aurelius aurelius && \
    chown -R aurelius:aurelius /app
USER aurelius

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

EXPOSE 3001

CMD ["npx", "tsx", "watch", "src/index.ts"]
