"""Aurelius — Constitutional AI Trainer.

Bai et al. (2022) "Constitutional AI: Harmlessness from AI Feedback"
https://arxiv.org/abs/2212.08073

CAI has two phases:

**Phase 1 — Supervised Learning from AI Feedback (SL-CAF):**
  1. Generate initial response.
  2. Critique: "Is this harmful?  Which principle does it violate?"
  3. Revise: "Revise to be more helpful and harmless."
  4. Train on revised responses via SFT (negative log-likelihood).

**Phase 2 — RL from AI Feedback (RLAIF):**
  Preference labels are generated by an AI judge guided by the same
  constitutional principles; a reward model is then trained and used for
  standard RLHF.  This module implements Phase 1 loss computation and the
  data structures shared by both phases.

The actual LLM calls (generation, critique, revision) are *not* implemented
here — only the loss functions and scoring heuristics that sit atop them.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import torch


# ---------------------------------------------------------------------------
# Principles enum
# ---------------------------------------------------------------------------


class CAIPrinciple(Enum):
    """Core constitutional principles used to evaluate responses."""

    HARMLESS = "harmless"
    HONEST = "honest"
    HELPFUL = "helpful"


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class CAIConfig:
    """Configuration for CAITrainer.

    Attributes:
        n_revisions:          Number of critique-revise cycles to perform.
        revision_weight:      Weight applied to the SFT loss on revised
                              responses (higher = prioritise fixing).
        critique_weight:      Weight applied to the SFT loss on critiques
                              (typically lower — critiques are auxiliary).
        principles:           Which constitutional principles to check.
                              Defaults to all three CAIPrinciple values.
        max_critique_tokens:  Maximum token budget for a single critique.
    """

    n_revisions: int = 2
    revision_weight: float = 1.0
    critique_weight: float = 0.5
    principles: list[str] = field(
        default_factory=lambda: [p.value for p in CAIPrinciple]
    )
    max_critique_tokens: int = 256


# ---------------------------------------------------------------------------
# Example / Batch data structures
# ---------------------------------------------------------------------------


@dataclass
class CAIExample:
    """One critique-revise example produced during SL-CAF data generation.

    Attributes:
        original_response:  The model's initial (possibly harmful) response.
        critiques:          One critique string per revision round.
        revised_responses:  One revised response string per revision round.
        principle_violated: The constitutional principle that prompted the
                            first revision, or None if none was identified.
    """

    original_response: str
    critiques: list[str]
    revised_responses: list[str]
    principle_violated: Optional[str] = None


@dataclass
class CAIBatch:
    """Per-token log-probs and masks for a CAI training batch.

    All tensors are produced by running the policy over tokenised text and
    extracting the per-token log-probabilities of the ground-truth tokens.

    Attributes:
        original_log_probs: ``[B, T_orig]`` log-probs of original response.
        revised_log_probs:  ``[B, T_rev]``  log-probs of final revised
                             response (the training target).
        critique_log_probs: ``[B, T_crit]`` log-probs of the critique.
        original_mask:      ``[B, T_orig]`` binary mask (1 = valid, 0 = pad).
        revised_mask:       ``[B, T_rev]``  binary mask.
        critique_mask:      ``[B, T_crit]`` binary mask.
    """

    original_log_probs: torch.Tensor
    revised_log_probs: torch.Tensor
    critique_log_probs: torch.Tensor
    original_mask: torch.Tensor
    revised_mask: torch.Tensor
    critique_mask: torch.Tensor


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------


class CAITrainer:
    """Constitutional AI SFT trainer (Phase 1 — SL-CAF).

    Computes the weighted SFT loss over critique and revised-response tokens
    as described in Bai et al. (2022).  The combined objective is:

        L = revision_weight · NLL(revised) + critique_weight · NLL(critique)

    An *optional* KL regulariser away from the original response is supported
    (set ``kl_coeff > 0`` at call-time) but is not applied by default, matching
    the paper which uses pure SFT in Phase 1.

    Usage::

        config  = CAIConfig(n_revisions=2, revision_weight=1.0,
                            critique_weight=0.5)
        trainer = CAITrainer(config)

        batch = CAIBatch(
            original_log_probs=...,   # [B, T_orig]
            revised_log_probs=...,    # [B, T_rev]
            critique_log_probs=...,   # [B, T_crit]
            original_mask=...,        # [B, T_orig]
            revised_mask=...,         # [B, T_rev]
            critique_mask=...,        # [B, T_crit]
        )
        out = trainer.total_loss(batch)
        out["loss"].backward()
    """

    def __init__(self, config: CAIConfig | None = None) -> None:
        self.config = config if config is not None else CAIConfig()

    # ------------------------------------------------------------------
    # Core primitive
    # ------------------------------------------------------------------

    def sft_loss(
        self,
        log_probs: torch.Tensor,
        mask: torch.Tensor,
    ) -> torch.Tensor:
        """Negative log-likelihood over valid (non-padding) tokens.

        Computes the mean NLL across *all valid tokens* in the batch (not
        per-sequence then averaged — this gives equal weight to every token
        and is the standard SFT formulation).

        Args:
            log_probs: ``[B, T]`` per-token log-probabilities (all ≤ 0).
            mask:      ``[B, T]`` binary mask; 1 = valid token, 0 = padding.

        Returns:
            Scalar loss tensor (positive for negative log-probs).
        """
        total_lp = (log_probs * mask).sum()
        total_tokens = mask.sum().clamp(min=1)
        return -(total_lp / total_tokens)

    # ------------------------------------------------------------------
    # Heuristic quality scoring (operates on strings, no tensors needed)
    # ------------------------------------------------------------------

    def revision_quality_score(
        self,
        examples: list[CAIExample],
    ) -> dict[str, float]:
        """Heuristic quality metrics derived from critique-revise examples.

        Three metrics are returned:

        * **length_ratio** — mean(len(final_revised) / len(original)).
          A ratio > 1 indicates the revision added content; ratios closer to
          1 suggest the response was largely retained.
        * **revision_count** — mean number of revision rounds per example
          (i.e. ``len(example.revised_responses)``).
        * **critique_rate** — fraction of examples where ``principle_violated``
          is not None, indicating that a constitutional violation was detected.

        Args:
            examples: List of :class:`CAIExample` instances.

        Returns:
            Dict with keys ``"length_ratio"``, ``"revision_count"``,
            ``"critique_rate"``.
        """
        if not examples:
            return {"length_ratio": 0.0, "revision_count": 0.0, "critique_rate": 0.0}

        length_ratios: list[float] = []
        revision_counts: list[float] = []
        critique_flags: list[float] = []

        for ex in examples:
            orig_len = max(len(ex.original_response), 1)
            # Use the final revised response for the length ratio
            if ex.revised_responses:
                final_len = len(ex.revised_responses[-1])
            else:
                final_len = orig_len
            length_ratios.append(final_len / orig_len)
            revision_counts.append(float(len(ex.revised_responses)))
            critique_flags.append(1.0 if ex.principle_violated is not None else 0.0)

        n = len(examples)
        return {
            "length_ratio": sum(length_ratios) / n,
            "revision_count": sum(revision_counts) / n,
            "critique_rate": sum(critique_flags) / n,
        }

    # ------------------------------------------------------------------
    # Combined loss
    # ------------------------------------------------------------------

    def total_loss(
        self,
        batch: CAIBatch,
        kl_coeff: float = 0.0,
    ) -> dict[str, torch.Tensor]:
        """Compute the weighted SFT loss over revised responses and critiques.

        L = revision_weight · NLL(revised) + critique_weight · NLL(critique)

        An optional KL regulariser penalises the policy for moving *away* from
        the original response distribution (useful to prevent over-revision):

            L_kl = mean(-original_log_probs * original_mask) — this is the
                   cross-entropy of the policy evaluated on original tokens,
                   acting as a soft anchor.

        Args:
            batch:    :class:`CAIBatch` with per-token log-probs and masks.
            kl_coeff: Weight for the optional KL regulariser (default 0 = off).

        Returns:
            Dict with keys:

            * ``"loss"``          — combined scalar loss.
            * ``"revised_loss"``  — NLL on revised responses.
            * ``"critique_loss"`` — NLL on critiques.
        """
        cfg = self.config

        revised_loss = self.sft_loss(batch.revised_log_probs, batch.revised_mask)
        critique_loss = self.sft_loss(batch.critique_log_probs, batch.critique_mask)

        combined = cfg.revision_weight * revised_loss + cfg.critique_weight * critique_loss

        if kl_coeff > 0.0:
            # Soft anchor: penalise divergence from original response tokens
            kl_term = self.sft_loss(batch.original_log_probs, batch.original_mask)
            combined = combined + kl_coeff * kl_term

        return {
            "loss": combined,
            "revised_loss": revised_loss,
            "critique_loss": critique_loss,
        }

    # ------------------------------------------------------------------
    # Principle filter
    # ------------------------------------------------------------------

    def apply_principles_filter(
        self,
        example: CAIExample,
        principles: list[str],
    ) -> bool:
        """Check whether any constitutional principle is mentioned in critiques.

        Case-insensitive substring search over all critique strings for each
        principle name.  Returns ``True`` as soon as any principle is found in
        any critique, allowing early exit.

        Args:
            example:    :class:`CAIExample` containing the critique strings.
            principles: List of principle strings to search for (e.g.
                        ``["harmless", "honest"]``).

        Returns:
            ``True`` if at least one critique references at least one principle,
            ``False`` otherwise.
        """
        for critique in example.critiques:
            critique_lower = critique.lower()
            for principle in principles:
                if principle.lower() in critique_lower:
                    return True
        return False

    # ------------------------------------------------------------------
    # Statistics (no-grad diagnostics)
    # ------------------------------------------------------------------

    def statistics(self, batch: CAIBatch) -> dict[str, float]:
        """Compute diagnostic statistics for a batch (no gradient tracking).

        Args:
            batch: :class:`CAIBatch`.

        Returns:
            Dict with keys:

            * ``"revised_nll"``  — mean NLL on revised responses.
            * ``"critique_nll"`` — mean NLL on critiques.
            * ``"loss"``         — combined weighted loss (float).
        """
        with torch.no_grad():
            out = self.total_loss(batch)
        return {
            "revised_nll": out["revised_loss"].item(),
            "critique_nll": out["critique_loss"].item(),
            "loss": out["loss"].item(),
        }


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

from src.alignment import ALIGNMENT_REGISTRY  # noqa: E402

ALIGNMENT_REGISTRY["constitutional_ai"] = CAITrainer
