"""Aurelius -- SPIN: Self-Play Fine-Tuning (Chen et al. 2024).

The model iteratively improves by playing against a frozen copy of its previous
self. At iteration t, the current model pi_t learns to distinguish human-generated
responses from responses it generated at iteration t-1. No preference labels are
required -- only human demonstrations.

Reference:
    Self-Play Fine-Tuning Converts Weak Language Models to Strong Language Models
    Chen et al., 2024. https://arxiv.org/abs/2401.01335
"""

from __future__ import annotations

import copy

import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# SPIN Loss
# ---------------------------------------------------------------------------

class SPINLoss(nn.Module):
    """SPIN loss function.

    L_SPIN = -E[log sigma(beta * (log pi_t(y_real|x) - log pi_{t-1}(y_real|x))
                          - beta * (log pi_t(y_synth|x) - log pi_{t-1}(y_synth|x)))]

    Where:
    - y_real:  human-generated response
    - y_synth: response generated by pi_{t-1} (previous model)
    - pi_t:    current model (being trained)
    - pi_{t-1}: reference model (frozen copy of previous iteration)
    - beta:    temperature coefficient

    This is equivalent to DPO loss with y_real as "chosen" and y_synth as
    "rejected", but the reference model IS the previous iteration (not a
    separate RLHF ref model).

    Args:
        beta: Temperature coefficient. Default: 0.1.
    """

    def __init__(self, beta: float = 0.1) -> None:
        super().__init__()
        self.beta = beta

    def forward(
        self,
        policy_chosen_logps: torch.Tensor,
        policy_rejected_logps: torch.Tensor,
        ref_chosen_logps: torch.Tensor,
        ref_rejected_logps: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Compute SPIN loss.

        Args:
            policy_chosen_logps:   Log probs of real responses under current policy.  Shape (B,).
            policy_rejected_logps: Log probs of synthetic responses under current policy. Shape (B,).
            ref_chosen_logps:      Log probs of real responses under ref model.       Shape (B,).
            ref_rejected_logps:    Log probs of synthetic responses under ref model.  Shape (B,).

        Returns:
            Tuple of (loss, chosen_rewards, rejected_rewards):
                loss:             Scalar SPIN loss.
                chosen_rewards:   beta * (policy_chosen_logps  - ref_chosen_logps).   Shape (B,).
                rejected_rewards: beta * (policy_rejected_logps - ref_rejected_logps). Shape (B,).
        """
        chosen_rewards = self.beta * (policy_chosen_logps - ref_chosen_logps)
        rejected_rewards = self.beta * (policy_rejected_logps - ref_rejected_logps)
        loss = -F.logsigmoid(chosen_rewards - rejected_rewards).mean()
        return loss, chosen_rewards, rejected_rewards


# ---------------------------------------------------------------------------
# Token log-probability computation
# ---------------------------------------------------------------------------

def compute_token_log_probs(
    model: nn.Module,
    input_ids: torch.Tensor,
    response_ids: torch.Tensor,
    reduction: str = 'sum',
) -> torch.Tensor:
    """Compute sum/mean of log probabilities for response tokens.

    Steps:
        1. Concatenate input_ids and response_ids: (B, S+R)
        2. Run model forward to get logits
        3. Extract logits for response positions: logits[:, S-1:-1, :]
        4. Compute log_softmax and gather response token log probs
        5. Sum (or mean) over response length

    Args:
        model:        Model whose forward returns (loss, logits, present_key_values).
        input_ids:    Prompt token ids.  Shape (B, S).
        response_ids: Response token ids. Shape (B, R).
        reduction:    'sum' or 'mean' over response tokens. Default: 'sum'.

    Returns:
        Shape (B,) -- per-sequence log probability of the response.
    """
    if reduction not in ('sum', 'mean'):
        raise ValueError(f"reduction must be 'sum' or 'mean', got {reduction!r}")

    B, S = input_ids.shape
    _, R = response_ids.shape

    full_ids = torch.cat([input_ids, response_ids], dim=1)  # (B, S+R)

    _, logits, _ = model(full_ids)  # (B, S+R, vocab_size)

    # logits[:, t, :] predicts token at position t+1.
    # Response tokens start at position S in full_ids, predicted by logits at S-1.
    response_logits = logits[:, S - 1 : S + R - 1, :]  # (B, R, vocab_size)

    log_probs = F.log_softmax(response_logits, dim=-1)  # (B, R, vocab_size)

    token_log_probs = log_probs.gather(
        2, response_ids.unsqueeze(-1)
    ).squeeze(-1)  # (B, R)

    if reduction == 'sum':
        return token_log_probs.sum(dim=-1)   # (B,)
    else:
        return token_log_probs.mean(dim=-1)  # (B,)


# ---------------------------------------------------------------------------
# SPIN Trainer
# ---------------------------------------------------------------------------

class SPINTrainer:
    """SPIN training loop.

    Maintains:
    - policy_model: the model being trained (updates each step)
    - ref_model:    frozen copy of previous iteration (updated each SPIN iteration)

    Args:
        policy_model:   Model to train.
        ref_model:      Frozen reference model (deepcopy of previous policy).
        optimizer:      Optimizer for policy_model.
        beta:           SPIN temperature. Default: 0.1.
        max_gen_tokens: Max tokens to generate for synthetic responses. Default: 64.
    """

    def __init__(
        self,
        policy_model: nn.Module,
        ref_model: nn.Module,
        optimizer: torch.optim.Optimizer,
        beta: float = 0.1,
        max_gen_tokens: int = 64,
    ) -> None:
        self.policy_model = policy_model
        self.ref_model = ref_model
        self.optimizer = optimizer
        self.beta = beta
        self.max_gen_tokens = max_gen_tokens
        self.criterion = SPINLoss(beta=beta)

        for p in self.ref_model.parameters():
            p.requires_grad_(False)

    def generate_synthetic(self, prompt_ids: torch.Tensor) -> torch.Tensor:
        """Generate a synthetic response using ref_model (greedy, no_grad).

        Args:
            prompt_ids: Prompt token ids. Shape (1, prompt_len).

        Returns:
            Shape (1, max_gen_tokens) -- generated response token ids.
        """
        self.ref_model.eval()
        generated = []
        current_ids = prompt_ids  # (1, S)

        with torch.no_grad():
            for _ in range(self.max_gen_tokens):
                _, logits, _ = self.ref_model(current_ids)  # (1, S, V)
                next_token = logits[:, -1, :].argmax(dim=-1, keepdim=True)  # (1, 1)
                generated.append(next_token)
                current_ids = torch.cat([current_ids, next_token], dim=1)

        return torch.cat(generated, dim=1)  # (1, max_gen_tokens)

    def train_step(
        self,
        prompt_ids: torch.Tensor,
        real_response_ids: torch.Tensor,
    ) -> dict:
        """Run a single SPIN training step.

        1. Generate synthetic response from ref_model.
        2. Compute policy log probs for real and synthetic responses.
        3. Compute ref log probs for real and synthetic responses (no_grad).
        4. Compute SPIN loss.
        5. Backward + optimizer step.

        Args:
            prompt_ids:        Prompt token ids. Shape (1, prompt_len).
            real_response_ids: Human response token ids. Shape (1, response_len).

        Returns:
            Dict with keys: 'loss', 'chosen_reward', 'rejected_reward', 'reward_margin'.
        """
        synth_response_ids = self.generate_synthetic(prompt_ids)

        self.policy_model.train()
        policy_chosen_logps = compute_token_log_probs(
            self.policy_model, prompt_ids, real_response_ids, reduction='sum'
        )
        policy_rejected_logps = compute_token_log_probs(
            self.policy_model, prompt_ids, synth_response_ids, reduction='sum'
        )

        with torch.no_grad():
            ref_chosen_logps = compute_token_log_probs(
                self.ref_model, prompt_ids, real_response_ids, reduction='sum'
            )
            ref_rejected_logps = compute_token_log_probs(
                self.ref_model, prompt_ids, synth_response_ids, reduction='sum'
            )

        loss, chosen_rewards, rejected_rewards = self.criterion(
            policy_chosen_logps,
            policy_rejected_logps,
            ref_chosen_logps,
            ref_rejected_logps,
        )

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        chosen_reward = chosen_rewards.mean().item()
        rejected_reward = rejected_rewards.mean().item()

        return {
            'loss': loss.item(),
            'chosen_reward': chosen_reward,
            'rejected_reward': rejected_reward,
            'reward_margin': chosen_reward - rejected_reward,
        }

    def update_reference_model(self) -> None:
        """Copy current policy weights to ref_model (start of new SPIN iteration)."""
        self.ref_model.load_state_dict(
            copy.deepcopy(self.policy_model.state_dict())
        )
        for p in self.ref_model.parameters():
            p.requires_grad_(False)


# ---------------------------------------------------------------------------
# SPIN Data Collator
# ---------------------------------------------------------------------------

class SPINDataCollator:
    """Prepares batches for SPIN training."""

    def collate(
        self,
        prompts: list[torch.Tensor],
        real_responses: list[torch.Tensor],
    ) -> list[dict]:
        """Return list of {'prompt_ids': ..., 'real_response_ids': ...} dicts.

        Args:
            prompts:        List of prompt tensors.
            real_responses: List of human response tensors.

        Returns:
            List of dicts with keys 'prompt_ids' and 'real_response_ids'.
        """
        if len(prompts) != len(real_responses):
            raise ValueError(
                f"prompts and real_responses must have the same length, "
                f"got {len(prompts)} and {len(real_responses)}"
            )
        return [
            {'prompt_ids': p, 'real_response_ids': r}
            for p, r in zip(prompts, real_responses)
        ]
