"""Aurelius — SPIN Trainer: Self-Play Fine-Tuning Iteration.

Chen et al. (2024) "Self-Play Fine-Tuning Converts Weak Language Models to
Strong Language Models" — https://arxiv.org/abs/2401.01335 (Apache-2.0)

SPIN iteratively improves a policy model by learning to distinguish real
(human-generated) responses from responses generated by the previous iteration
of the model. No preference labels are required — only human demonstrations.

Each SPIN iteration trains pi_t against a frozen copy pi_{t-1}:

    L_SPIN = -E[log σ(β · (log r_real - log r_gen))]

    where log r = log π_θ(y|x) - log π_{t-1}(y|x)
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch import Tensor

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class SPINConfig:
    """Configuration for SPINTrainer.

    Attributes:
        learning_rate: Optimiser learning rate.
        lambda_reg:    Regularisation coefficient (informational; applied
                       externally if needed).
        n_iterations:  Number of SPIN outer iterations to run.
        batch_size:    Training batch size.
        max_seq_len:   Maximum sequence length in tokens.
        gamma:         Margin parameter (currently reserved; default 0.0).
        beta:          Temperature / KL coefficient for the SPIN objective.
    """

    learning_rate: float = 1e-6
    lambda_reg: float = 0.1
    n_iterations: int = 3
    batch_size: int = 4
    max_seq_len: int = 512
    gamma: float = 0.0
    beta: float = 0.1


# ---------------------------------------------------------------------------
# Batch
# ---------------------------------------------------------------------------


@dataclass
class SPINBatch:
    """A single SPIN training batch.

    Attributes:
        real_ids:       Token IDs for real (human) completions, shape B×L.
        generated_ids:  Token IDs for generated completions, shape B×L.
        real_mask:      Attention mask for real sequences, shape B×L or None.
        generated_mask: Attention mask for generated sequences, shape B×L or None.
    """

    real_ids: Tensor
    generated_ids: Tensor
    real_mask: Tensor | None = None
    generated_mask: Tensor | None = None


# ---------------------------------------------------------------------------
# Loss Module
# ---------------------------------------------------------------------------


class SPINLoss(nn.Module):
    """SPIN objective as a differentiable nn.Module.

    L = -E[log σ(β · (log r_real - log r_gen))]

    where log r_x = policy_logprobs_x - ref_logprobs_x (per-sequence).

    Args:
        beta: Temperature coefficient. Stored as a non-trainable buffer.
    """

    def __init__(self, beta: float = 0.1) -> None:
        super().__init__()
        self.register_buffer("beta", torch.tensor(beta, dtype=torch.float32))

    def forward(
        self,
        policy_logprobs_real: Tensor,
        policy_logprobs_gen: Tensor,
        ref_logprobs_real: Tensor,
        ref_logprobs_gen: Tensor,
    ) -> Tensor:
        """Compute the SPIN loss.

        Args:
            policy_logprobs_real: Per-sequence log-probs (policy, real). Shape (B,).
            policy_logprobs_gen:  Per-sequence log-probs (policy, generated). Shape (B,).
            ref_logprobs_real:    Per-sequence log-probs (reference, real). Shape (B,).
            ref_logprobs_gen:     Per-sequence log-probs (reference, generated). Shape (B,).

        Returns:
            Scalar loss tensor.
        """
        logr_real = policy_logprobs_real - ref_logprobs_real  # (B,)
        logr_gen = policy_logprobs_gen - ref_logprobs_gen  # (B,)
        logits = self.beta * (logr_real - logr_gen)  # (B,)
        return -F.logsigmoid(logits).mean()


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------


class SPINTrainer:
    """SPIN iteration trainer: policy model vs. frozen reference.

    The trainer holds a policy model being trained and a frozen reference model
    (copy of the previous SPIN iteration). Each training step computes the SPIN
    loss and applies one gradient update.

    Args:
        policy:    The trainable policy model (nn.Module).
        ref_model: Frozen reference model from the previous iteration (nn.Module).
        cfg:       SPINConfig with hyperparameters.
        optimizer: Optimiser for the policy model parameters.
    """

    def __init__(
        self,
        policy: nn.Module,
        ref_model: nn.Module,
        cfg: SPINConfig,
        optimizer: optim.Optimizer,
    ) -> None:
        self.policy = policy
        self.ref_model = ref_model
        self.cfg = cfg
        self.optimizer = optimizer
        self._loss_fn = SPINLoss(beta=cfg.beta)

        # Freeze reference model
        for p in self.ref_model.parameters():
            p.requires_grad_(False)

    # ------------------------------------------------------------------
    # Core primitive
    # ------------------------------------------------------------------

    def compute_logprobs(
        self,
        model: nn.Module,
        input_ids: Tensor,
        labels: Tensor,
        mask: Tensor | None,
    ) -> Tensor:
        """Compute per-sequence mean log-probabilities.

        Performs a forward pass through *model*, extracts per-token log-probs
        for the positions specified by *labels*, masks padding positions, and
        returns the mean over non-padding tokens for each sequence.

        Args:
            model:     A causal LM; forward(input_ids) → logits (B, T, V).
            input_ids: Token IDs, shape (B, T).
            labels:    Target token IDs, shape (B, T). Use -100 to mask a position.
            mask:      Optional binary mask (B, T); 1 = valid, 0 = padding.
                       If None, positions where labels != -100 are used.

        Returns:
            Per-sequence mean log-prob, shape (B,).
        """
        logits = model(input_ids)  # (B, T, V)
        log_probs = F.log_softmax(logits, dim=-1)  # (B, T, V)

        labels_clamped = labels.clamp(min=0)  # (B, T)
        token_lp = log_probs.gather(dim=2, index=labels_clamped.unsqueeze(-1)).squeeze(-1)  # (B, T)

        if mask is not None:
            valid = mask.float()
        else:
            valid = (labels != -100).float()  # (B, T)

        valid_count = valid.sum(dim=-1).clamp(min=1.0)  # (B,)
        return (token_lp * valid).sum(dim=-1) / valid_count  # (B,)

    # ------------------------------------------------------------------
    # Training interface
    # ------------------------------------------------------------------

    def train_step(self, batch: SPINBatch) -> dict[str, float]:
        """Perform one SPIN gradient update.

        Computes policy and reference log-probs for both real and generated
        sequences, evaluates the SPIN loss, and applies one optimiser step.

        Args:
            batch: SPINBatch containing real and generated token IDs + masks.

        Returns:
            Dict with keys:
            - ``"loss"``      — scalar training loss.
            - ``"logr_real"`` — mean log-ratio for real sequences.
            - ``"logr_gen"``  — mean log-ratio for generated sequences.
        """
        self.policy.train()

        # Use input_ids as labels (next-token prediction; mask handled by mask tensor)
        real_labels = batch.real_ids
        gen_labels = batch.generated_ids

        # Policy log-probs (differentiable)
        policy_lp_real = self.compute_logprobs(
            self.policy, batch.real_ids, real_labels, batch.real_mask
        )
        policy_lp_gen = self.compute_logprobs(
            self.policy, batch.generated_ids, gen_labels, batch.generated_mask
        )

        # Reference log-probs (no gradient)
        with torch.no_grad():
            ref_lp_real = self.compute_logprobs(
                self.ref_model, batch.real_ids, real_labels, batch.real_mask
            )
            ref_lp_gen = self.compute_logprobs(
                self.ref_model, batch.generated_ids, gen_labels, batch.generated_mask
            )

        loss = self._loss_fn(policy_lp_real, policy_lp_gen, ref_lp_real, ref_lp_gen)

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        with torch.no_grad():
            logr_real = (policy_lp_real - ref_lp_real).mean().item()
            logr_gen = (policy_lp_gen - ref_lp_gen).mean().item()

        return {
            "loss": loss.item(),
            "logr_real": logr_real,
            "logr_gen": logr_gen,
        }

    def iteration(self, batches: list[SPINBatch]) -> dict[str, float]:
        """Run one full SPIN iteration over a list of batches.

        Processes every batch in sequence, accumulates metrics, and returns
        the mean of each metric across all batches.

        Args:
            batches: List of SPINBatch objects for this iteration.

        Returns:
            Dict with mean values for ``"loss"``, ``"logr_real"``, ``"logr_gen"``.
        """
        accum: dict[str, float] = {"loss": 0.0, "logr_real": 0.0, "logr_gen": 0.0}
        n = len(batches)
        if n == 0:
            return accum

        for batch in batches:
            metrics = self.train_step(batch)
            for k, v in metrics.items():
                accum[k] += v

        return {k: v / n for k, v in accum.items()}


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

from src.alignment import ALIGNMENT_REGISTRY  # noqa: E402

ALIGNMENT_REGISTRY["spin"] = SPINTrainer
