"""Aurelius — STaR: Self-Taught Reasoner (Zelikman et al., arXiv:2203.14465).

STaR bootstraps chain-of-thought reasoning by:
1. Generating rationale + answer pairs from a model.
2. Filtering to keep only correct answers.
3. Falling back to rationalization (hint-conditioned) for incorrect ones.
4. Fine-tuning on all correct (question + rationale + answer) triples via SFT.
5. Iterating until convergence.

This module implements the core algorithmic components as pure PyTorch
primitives — no external alignment libraries required.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# STaRSample — data container
# ---------------------------------------------------------------------------


@dataclass
class STaRSample:
    """A single STaR training sample.

    Attributes:
        question: The input problem/question string.
        rationale: The chain-of-thought rationale string generated by the model.
        answer: The final answer string extracted from the model output.
        is_correct: Whether the answer matches the ground-truth answer.
        from_rationalization: True when the sample was produced via the
            rationalization fallback (conditioned on the correct answer hint),
            rather than free generation.
    """

    question: str
    rationale: str
    answer: str
    is_correct: bool
    from_rationalization: bool = False


# ---------------------------------------------------------------------------
# STaRFilter — correctness-based filtering
# ---------------------------------------------------------------------------


class STaRFilter:
    """Filters STaRSample lists by correctness and computes accuracy.

    Args:
        answer_extractor: Optional callable ``(sample: STaRSample) -> bool``
            that decides whether a sample is correct.  When *None*, the filter
            relies solely on the pre-computed ``sample.is_correct`` flag (which
            callers should have set using exact string match on the last token,
            or any other external oracle).
    """

    def __init__(
        self,
        answer_extractor: Optional[Callable[[STaRSample], bool]] = None,
    ) -> None:
        self.answer_extractor = answer_extractor

    def _is_correct(self, sample: STaRSample) -> bool:
        """Return True if *sample* should be considered correct.

        If an ``answer_extractor`` was provided it overrides ``is_correct``;
        otherwise ``sample.is_correct`` is used directly.
        """
        if self.answer_extractor is not None:
            return self.answer_extractor(sample)
        return sample.is_correct

    def filter(self, samples: List[STaRSample]) -> List[STaRSample]:
        """Return only the samples deemed correct.

        Args:
            samples: List of :class:`STaRSample` objects (may be empty).

        Returns:
            A new list containing only samples for which :meth:`_is_correct`
            returns ``True``.
        """
        return [s for s in samples if self._is_correct(s)]

    def compute_accuracy(self, samples: List[STaRSample]) -> float:
        """Compute the fraction of correct samples.

        Args:
            samples: List of :class:`STaRSample` objects.

        Returns:
            Fraction in [0.0, 1.0].  Returns 0.0 on an empty list to avoid
            division-by-zero.
        """
        if not samples:
            return 0.0
        n_correct = sum(1 for s in samples if self._is_correct(s))
        return n_correct / len(samples)


# ---------------------------------------------------------------------------
# STaRLoss — SFT NLL loss with question-prefix masking
# ---------------------------------------------------------------------------


class STaRLoss(nn.Module):
    """Computes the SFT (negative log-likelihood) loss for STaR fine-tuning.

    Only rationale+answer tokens contribute to the loss when
    ``ignore_question_tokens=True``; question-prefix positions are masked with
    ``label=-100`` so they are excluded from the cross-entropy.

    Args:
        ignore_question_tokens: When ``True`` (default), the loss is computed
            only over positions *after* the question prefix.  When ``False``,
            all positions contribute (standard causal LM cross-entropy).
    """

    def __init__(self, ignore_question_tokens: bool = True) -> None:
        super().__init__()
        self.ignore_question_tokens = ignore_question_tokens

    def forward(
        self,
        logits: torch.Tensor,
        token_ids: torch.Tensor,
        question_lengths: torch.Tensor,
    ) -> torch.Tensor:
        """Compute the mean cross-entropy loss over unmasked positions.

        Args:
            logits: Float tensor of shape ``(B, T, V)`` — raw model logits.
            token_ids: Long tensor of shape ``(B, T)`` — ground-truth token IDs.
            question_lengths: Long tensor of shape ``(B,)`` — number of
                question-prefix tokens to mask per sample.  A value ``>= T``
                masks the entire sequence, resulting in a loss of 0.0.

        Returns:
            Scalar loss tensor (mean over all unmasked positions across the
            batch).  Returns ``torch.tensor(0.0)`` if every position is masked.
        """
        B, T, V = logits.shape

        # Build label tensor; start from token_ids
        labels = token_ids.clone()  # (B, T)

        if self.ignore_question_tokens:
            # Mask question-prefix positions with -100 for each sample
            for i in range(B):
                q_len = int(question_lengths[i].item())
                # Clamp to [0, T] to avoid out-of-range slicing
                q_len = max(0, min(q_len, T))
                labels[i, :q_len] = -100

        # Standard causal LM: predict token t from logit at position t-1.
        # Shift: logits[:, :-1, :] predicts token_ids[:, 1:]
        shift_logits = logits[:, :-1, :].contiguous()   # (B, T-1, V)
        shift_labels = labels[:, 1:].contiguous()        # (B, T-1)

        # Flatten for F.cross_entropy
        flat_logits = shift_logits.view(-1, V)           # (B*(T-1), V)
        flat_labels = shift_labels.view(-1)              # (B*(T-1),)

        # Guard: if every position is masked (all labels == -100), PyTorch's
        # cross_entropy returns NaN.  Return 0.0 in that case instead.
        if (flat_labels == -100).all():
            return flat_logits.sum() * 0.0  # preserves grad_fn if logits require grad

        loss = F.cross_entropy(flat_logits, flat_labels, ignore_index=-100)
        return loss


# ---------------------------------------------------------------------------
# STaRTrainer — orchestrates one iteration of STaR
# ---------------------------------------------------------------------------


class STaRTrainer:
    """Orchestrates one full STaR iteration: fine-tuning + rationalization stats.

    Args:
        model: A ``torch.nn.Module`` whose parameters will be optimised.
        optimizer: A ``torch.optim.Optimizer`` bound to ``model``'s parameters.
        loss_fn: A :class:`STaRLoss` (or compatible callable) used for the SFT
            objective.
    """

    def __init__(
        self,
        model: nn.Module,
        optimizer: torch.optim.Optimizer,
        loss_fn: STaRLoss,
    ) -> None:
        self.model = model
        self.optimizer = optimizer
        self.loss_fn = loss_fn

    def train_on_samples(self, batches: List[Dict[str, torch.Tensor]]) -> float:
        """Fine-tune the model on a list of pre-computed batches.

        Each element of *batches* must be a ``dict`` with the following keys:

        * ``"logits"`` — ``torch.Tensor`` of shape ``(B, T, V)``
        * ``"token_ids"`` — ``torch.Tensor`` of shape ``(B, T)``
        * ``"question_lengths"`` — ``torch.Tensor`` of shape ``(B,)``

        The method performs one gradient-update pass per batch (no gradient
        accumulation across batches).

        Args:
            batches: List of batch dicts as described above.

        Returns:
            Mean loss (Python ``float``) averaged over all batches.
        """
        if not batches:
            return 0.0

        self.model.train()
        total_loss = 0.0

        for batch in batches:
            logits: torch.Tensor = batch["logits"]
            token_ids: torch.Tensor = batch["token_ids"]
            question_lengths: torch.Tensor = batch["question_lengths"]

            self.optimizer.zero_grad()
            loss = self.loss_fn(logits, token_ids, question_lengths)
            # Only call backward when the loss is part of a computation graph
            # (i.e., it has a grad_fn).  If logits were detached or pre-computed
            # the loss may be a leaf constant; skipping backward in that case
            # avoids a RuntimeError while still accumulating the loss value.
            if loss.requires_grad:
                loss.backward()
                self.optimizer.step()

            total_loss += loss.item()

        return total_loss / len(batches)

    def rationalize_step(self, correct_frac: float, total: int) -> Dict[str, object]:
        """Compute rationalization statistics for one STaR iteration.

        In a full STaR loop the caller would have already generated samples,
        filtered them, and run the rationalization pass.  This method provides
        a lightweight summary of those numbers.

        Args:
            correct_frac: Fraction of problems answered correctly (in [0, 1]).
            total: Total number of problems attempted in this iteration.

        Returns:
            A ``dict`` with keys:

            * ``"n_total"`` — total problems (int)
            * ``"n_correct"`` — number answered correctly (int)
            * ``"n_rationalized"`` — number sent to the rationalization fallback (int)
            * ``"accuracy"`` — ``correct_frac`` (float)
        """
        n_correct = int(round(correct_frac * total))
        n_rationalized = total - n_correct

        stats: Dict[str, object] = {
            "n_total": total,
            "n_correct": n_correct,
            "n_rationalized": n_rationalized,
            "accuracy": correct_frac,
        }

        logger.info(
            "STaR iteration: total=%d correct=%d rationalized=%d accuracy=%.4f",
            total,
            n_correct,
            n_rationalized,
            correct_frac,
        )

        return stats
