"""Backtranslation pipeline for synthetic parallel data generation.

Generates synthetic instruction-following data by:
1. Taking monolingual source texts
2. Generating "instructions" that would produce those texts as responses
3. Creating (instruction, response) pairs for fine-tuning

Based on the Backtranslation / Self-Instruct data augmentation paradigm.
Pure Python — no external APIs.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------


@dataclass
class BacktranslationSample:
    """A synthetic (instruction, response) pair generated by backtranslation."""

    instruction: str
    response: str
    source_text: str  # original monolingual text used as "response"
    source_language: str = "en"
    target_language: str = "en"
    quality_score: float = 0.0
    is_synthetic: bool = True


@dataclass
class BacktranslationConfig:
    """Configuration for the backtranslation pipeline."""

    source_language: str = "en"
    target_language: str = "en"
    min_source_length: int = 20  # chars
    max_source_length: int = 2000
    min_instruction_length: int = 10
    dedup_threshold: float = 0.9  # ROUGE-L threshold for filtering near-duplicates
    n_instructions_per_source: int = 1  # how many instructions to generate per source
    filter_low_quality: bool = True
    quality_threshold: float = 0.3


# ---------------------------------------------------------------------------
# Instruction generation templates
# ---------------------------------------------------------------------------

_BACKTRANSLATION_PROMPT_TEMPLATES = [
    (
        "Below is a text passage. Write an instruction that someone would give "
        "to an AI assistant to produce this passage as the response.\n\n"
        "Passage:\n{text}\n\nInstruction:"
    ),
    (
        "What question or instruction would lead an AI to generate the following "
        "response? Provide only the instruction.\n\nResponse:\n{text}\n\nInstruction:"
    ),
    (
        "Reverse-engineer the following AI response into an instruction prompt. "
        "The instruction should be natural and specific.\n\nAI Response:\n{text}\n\nInstruction:"
    ),
]


def build_backtranslation_prompt(
    source_text: str,
    template_idx: int = 0,
) -> str:
    """Build a prompt to generate an instruction from a source text.

    Args:
        source_text: The text to "reverse" into an instruction.
        template_idx: Which prompt template to use (0-indexed).

    Returns:
        Formatted prompt string.
    """
    idx = template_idx % len(_BACKTRANSLATION_PROMPT_TEMPLATES)
    return _BACKTRANSLATION_PROMPT_TEMPLATES[idx].format(text=source_text.strip())


# ---------------------------------------------------------------------------
# Quality scoring
# ---------------------------------------------------------------------------


def _word_count(text: str) -> int:
    return len(text.split())


def _ends_with_question_or_imperative(text: str) -> bool:
    """Heuristic: good instructions often end with '?' or an imperative verb."""
    stripped = text.strip()
    if stripped.endswith("?"):
        return True
    # Check for imperative-like starters
    first_word = stripped.split()[0].lower() if stripped.split() else ""
    imperative_starters = {
        "write",
        "explain",
        "describe",
        "list",
        "compare",
        "analyze",
        "summarize",
        "generate",
        "create",
        "provide",
        "give",
        "what",
        "how",
        "why",
        "when",
        "translate",
        "calculate",
        "find",
        "identify",
    }
    return first_word in imperative_starters


def score_instruction_quality(
    instruction: str,
    source_text: str,
) -> float:
    """Score the quality of a backtranslated instruction.

    Combines: length score, question/imperative check, word overlap with source.

    Returns float in [0, 1].
    """
    if not instruction or not instruction.strip():
        return 0.0

    n_words = _word_count(instruction)

    # Length: penalize very short or very long instructions
    if n_words < 3:
        length_score = 0.0
    elif n_words <= 30:
        length_score = min(n_words / 10.0, 1.0)
    else:
        length_score = max(0.0, 1.0 - (n_words - 30) / 50.0)

    # Form score: ends with ? or imperative
    form_score = 1.0 if _ends_with_question_or_imperative(instruction) else 0.3

    # Relevance: some word overlap with source text (but not too much = just copying)
    src_words = set(source_text.lower().split())
    instr_words = set(instruction.lower().split())
    overlap = len(src_words & instr_words)
    n_src = max(len(src_words), 1)
    overlap_ratio = overlap / n_src
    # Ideal overlap: some (0.05–0.3), not too much
    if overlap_ratio < 0.02:
        relevance_score = 0.2
    elif overlap_ratio <= 0.3:
        relevance_score = 1.0
    else:
        relevance_score = max(0.2, 1.0 - overlap_ratio)

    return 0.4 * length_score + 0.3 * form_score + 0.3 * relevance_score


# ---------------------------------------------------------------------------
# Deduplication
# ---------------------------------------------------------------------------


def _rouge_l_f1(hyp: str, ref: str) -> float:
    """Lightweight ROUGE-L F1 using LCS (token-level)."""
    a = hyp.lower().split()
    b = ref.lower().split()
    if not a or not b:
        return 0.0
    # DP LCS
    m, n = len(a), len(b)
    prev = [0] * (n + 1)
    for i in range(m):
        curr = [0] * (n + 1)
        for j in range(n):
            if a[i] == b[j]:
                curr[j + 1] = prev[j] + 1
            else:
                curr[j + 1] = max(curr[j], prev[j + 1])
        prev = curr
    lcs = prev[n]
    p = lcs / len(a)
    r = lcs / len(b)
    if p + r < 1e-9:
        return 0.0
    return 2 * p * r / (p + r)


def deduplicate_samples(
    samples: list[BacktranslationSample],
    threshold: float = 0.9,
) -> list[BacktranslationSample]:
    """Remove near-duplicate samples based on ROUGE-L of instructions.

    Args:
        samples: Input samples.
        threshold: ROUGE-L similarity above which a sample is considered duplicate.

    Returns:
        Deduplicated list preserving order.
    """
    kept: list[BacktranslationSample] = []
    for candidate in samples:
        is_dup = False
        for accepted in kept:
            if _rouge_l_f1(candidate.instruction, accepted.instruction) >= threshold:
                is_dup = True
                break
        if not is_dup:
            kept.append(candidate)
    return kept


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


class BacktranslationPipeline:
    """Generate synthetic instruction-following data via backtranslation.

    Given a list of monolingual text passages, generates instructions that
    would produce those passages as responses.

    Args:
        generate_fn: Callable that takes a prompt string and returns generated text.
        config: BacktranslationConfig.
    """

    def __init__(
        self,
        generate_fn: Callable[[str], str],
        config: BacktranslationConfig | None = None,
    ) -> None:
        self.generate_fn = generate_fn
        self.config = config or BacktranslationConfig()

    def _passes_length_filter(self, text: str) -> bool:
        cfg = self.config
        return cfg.min_source_length <= len(text) <= cfg.max_source_length

    def generate_instruction(
        self,
        source_text: str,
        template_idx: int = 0,
    ) -> str:
        """Generate one instruction for the given source text."""
        prompt = build_backtranslation_prompt(source_text, template_idx)
        raw = self.generate_fn(prompt)
        # Clean: take first sentence/line as the instruction
        lines = [line.strip() for line in raw.strip().split("\n") if line.strip()]
        return lines[0] if lines else raw.strip()

    def process_source(
        self,
        source_text: str,
    ) -> list[BacktranslationSample]:
        """Generate BacktranslationSamples from a single source text.

        Returns empty list if text fails length filter.
        """
        if not self._passes_length_filter(source_text):
            return []

        cfg = self.config
        samples: list[BacktranslationSample] = []

        for i in range(cfg.n_instructions_per_source):
            instruction = self.generate_instruction(source_text, template_idx=i)

            if len(instruction) < cfg.min_instruction_length:
                continue

            quality = score_instruction_quality(instruction, source_text)

            if cfg.filter_low_quality and quality < cfg.quality_threshold:
                continue

            samples.append(
                BacktranslationSample(
                    instruction=instruction,
                    response=source_text,
                    source_text=source_text,
                    source_language=cfg.source_language,
                    target_language=cfg.target_language,
                    quality_score=quality,
                )
            )

        return samples

    def run(
        self,
        source_texts: list[str],
        deduplicate: bool = True,
    ) -> list[BacktranslationSample]:
        """Process all source texts and return generated samples.

        Args:
            source_texts: List of monolingual passages.
            deduplicate: Whether to remove near-duplicate instructions.

        Returns:
            List of BacktranslationSample sorted by quality score descending.
        """
        all_samples: list[BacktranslationSample] = []
        for text in source_texts:
            all_samples.extend(self.process_source(text))

        if deduplicate:
            all_samples = deduplicate_samples(all_samples, self.config.dedup_threshold)

        all_samples.sort(key=lambda s: s.quality_score, reverse=True)
        return all_samples

    def get_stats(
        self,
        samples: list[BacktranslationSample],
    ) -> dict[str, float]:
        """Compute summary statistics over generated samples."""
        if not samples:
            return {
                "n_samples": 0.0,
                "mean_quality": 0.0,
                "mean_instruction_len": 0.0,
                "mean_response_len": 0.0,
            }
        n = len(samples)
        return {
            "n_samples": float(n),
            "mean_quality": sum(s.quality_score for s in samples) / n,
            "mean_instruction_len": sum(len(s.instruction) for s in samples) / n,
            "mean_response_len": sum(len(s.response) for s in samples) / n,
        }
